### ISSUE TITLE
MaxLengthEnforcement error

### ISSUE THREAD

**Issue by Ronjack** [lzhuor/auto_size_text_field#30]
because of Flutter 3.0.0

![image](https://user-images.githubusercontent.com/16069241/168039444-d885b774-838b-41d9-bbcc-31137134633b.png)

temporary fixed with 

https://docs.flutter.dev/release/breaking-changes/use-maxLengthEnforcement-instead-of-maxLengthEnforced

**Comment by Ronjack** [comment]
![image](https://user-images.githubusercontent.com/16069241/168039881-40b78141-6c1e-4b80-ab6b-ef82095892a1.png)

**Comment by stepushchik-denis-gismart** [comment]
This is a duplicate of https://github.com/lzhuor/auto_size_text_field/issues/28

You can use this until there is a new version
```

  auto_size_text_field:
    git:
      url: https://github.com/stepushchik-denis-gismart/auto_size_text_field.git
      ref: c428f7ffefa8a385e2109e0997f4c9f5397262a5
```
